export enum ErrorCode {
  INVALID_LOGIN = 'INVALID_LOGIN',
  DUPLICATED_USERNAME = 'DUPLICATED_USERNAME',
  DUPLICATED_LOGIN_ID = 'DUPLICATED_LOGIN_ID',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  NOT_FOUND_TAG = 'NOT_FOUND_TAG',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  NOT_FOUND_TODO = 'NOT_FOUND_TODO',
  END_REPEAT_NECESSARY = 'END_REPEAT_NECESSARY',
  INVALID_STATUS = 'INVALID_STATUS',
}
